const assert = require("assert");
const solve = require("./app");
const { runExercise } = require("../../tests/shared/api-test-utils");

runExercise({
  solve,
  validate(result) {
    if (result !== "2026-04-13T00:00:00.000Z") {
      assert.fail(`Expected the created item audit timestamp to be "2026-04-13T00:00:00.000Z", but received ${JSON.stringify(result)}.`);
    }
  },
  negativeCheck(result) {
    if (result === "2025-01-01T00:00:00.000Z") {
      assert.fail("You returned a timestamp-shaped value, but not the one generated by the POST response in this exercise.");
    }
  }
}).catch((error) => {
  console.error(error);
  process.exit(1);
});
